language: python

sudo: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-sqlalchemy
    - python: 2.7
      env: TOXENV=py27-django-dj18
    - python: 2.7
      env: TOXENV=py27-django-dj19
    - python: 2.7
      env: TOXENV=py27-django-dj110
    - python: 2.7
      env: TOXENV=py27-django-dj111

    - python: 3.6
      env: TOXENV=py36-django-dj18
    - python: 3.6
      env: TOXENV=py36-django-dj19
    - python: 3.6
      env: TOXENV=py36-django-dj110
    - python: 3.6
      env: TOXENV=py36-django-dj111
    - python: 3.6
      env: TOXENV=py36-django-dj20
    - python: 3.6
      env: TOXENV=py36-django-dj21
    - python: 3.6
      env: TOXENV=py36-sqlalchemy

    - python: pypy
      env: TOXENV=pypy2-django-dj18
    - python: pypy
      env: TOXENV=pypy2-django-dj19
    - python: pypy
      env: TOXENV=pypy2-django-dj110
    - python: pypy
      env: TOXENV=pypy2-django-dj111
    - python: pypy
      env: TOXENV=pypy2-sqlalchemy

    - python: pypy3
      env: TOXENV=pypy3-django-dj18
    - python: pypy3
      env: TOXENV=pypy3-django-dj19
    - python: pypy3
      env: TOXENV=pypy3-django-dj110
    - python: pypy3
      env: TOXENV=pypy3-django-dj111
    - python: pypy3
      env: TOXENV=pypy3-django-dj20
    - python: pypy3
      env: TOXENV=pypy3-django-dj21
    - python: pypy3
      env: TOXENV=pypy3-sqlalchemy

    - python: 3.6
      env: TOXENV=py36-lint

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
