language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - USE_DEPS=1
  - USE_DEPS=0

install:
  - if [[ $USE_DEPS == 1 ]]; then pip install -r requirements-test.txt -r requirements-deps.txt; fi
  - if [[ $USE_DEPS == 0 ]]; then pip install -r requirements-test.txt; fi
  - pip install coveralls

script: py.test --flake8 --cov coolfig

after_success: coveralls
