language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - USE_SQLALCHEMY=1
  - USE_SQLALCHEMY=0

install:
  - if [[ $USE_SQLALCHEMY == 1 ]]; then pip install sqlalchemy; fi
  - pip install -r requirements-test.txt
  - pip install coveralls

script: py.test --pep8 --cov coolfig

after_success: coveralls
