language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"

sudo: false

env:
  matrix:
    - TOXENV=py27-sqlalchemy
    - TOXENV=py36-sqlalchemy
    - TOXENV=pypy2-sqlalchemy
    - TOXENV=py27-django-dj18
    - TOXENV=py27-django-dj19
    - TOXENV=py27-django-dj110
    - TOXENV=py27-django-dj111
    - TOXENV=pypy2-django-dj18
    - TOXENV=pypy2-django-dj19
    - TOXENV=pypy2-django-dj110
    - TOXENV=pypy2-django-dj111
    - TOXENV=py36-django-dj18
    - TOXENV=py36-django-dj19
    - TOXENV=py36-django-dj110
    - TOXENV=py36-django-dj111
    - TOXENV=py36-django-dj20
    - TOXENV=py36-django-dj21
    - TOXENV=pypy3-django-dj18
    - TOXENV=pypy3-django-dj19
    - TOXENV=pypy3-django-dj110
    - TOXENV=pypy3-django-dj111
    - TOXENV=pypy3-django-dj20
    - TOXENV=pypy3-django-dj21
    - TOXENV=py36-lint

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
