language: python

sudo: false

env:
  matrix:
    - TOXENV=py27-sqlalchemy
    - TOXENV=py34-sqlalchemy
    - TOXENV=pypy19-sqlalchemy
    - TOXENV=py27-django-dj15
    - TOXENV=py27-django-dj16
    - TOXENV=py27-django-dj17
    - TOXENV=py27-django-dj18
    - TOXENV=py34-django-dj15
    - TOXENV=py34-django-dj16
    - TOXENV=py34-django-dj17
    - TOXENV=py34-django-dj18
    - TOXENV=pypy19-django-dj15
    - TOXENV=pypy19-django-dj16
    - TOXENV=pypy19-django-dj17
    - TOXENV=pypy19-django-dj18
    - TOXENV=py27-django-dj14
    - TOXENV=pypy19-django-dj14
    - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
